#!/bin/bash

#SBATCH --job-name parallel_run_11ad_sem
#SBATCH --output parallel_run_11ad_sem.o%j
#SBATCH --error parallel_run_11ad_sem.e%j
#SBATCH --mail-user leccimat@dei.unipd.it
#SBATCH --mail-type ALL
#SBATCH
#SBATCH --time 365-00:00:00
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 32
#SBATCH --partition allgroups
#SBATCH --exclude runner-[04-08,13-15,16-19],gpu1,gpu2
#SBATCH --mem 64G

cd $SLURM_SUBMIT_DIR

# simulation parameters
CORES=32
NUM_RUNS=30
CAMPAIGN_NAME=b22fa0

# activate conda env
source /nfsd/opt/anaconda37/anaconda.sh
source activate /nfsd/signet3/leccimat/private/conda_envs/11ad-env

# compile ns-3
# NOTE: the optimized and release builds are not working properly on the blade
./waf configure -d debug --out=build/ --disable-examples --disable-tests --disable-python --enable-modules='applications','core','internet','point-to-point','wifi','flow-monitor','spectrum' --enable-static
# CXXFLAGS="-Wall" ./waf configure -d optimized --out=build/optimized --disable-examples --disable-tests --disable-python --enable-modules='applications','core','internet','point-to-point','wifi','flow-monitor','spectrum' --enable-static
# CXXFLAGS="-Wall" ./waf configure -d release --out=build/optimized --disable-examples --disable-tests --disable-python --enable-modules='applications','core','internet','point-to-point','wifi','flow-monitor','spectrum' --enable-static
./waf build

declare -a PARAM_SETS=("burst_smartOn" "burst_smartOff_cbapOn" "burst_smartOff_cbapOff" "burst_stdev_smartOn" "burst_stdev_smartOff_cbapOn" "burst_stdev_smartOff_cbapOff" "burstPeriodicity" "numStas")
for PARAM_SET in "${PARAM_SETS[@]}"; do
  ## Joint run and plot
  srun python3 sem-conference-showcase.py --cores=$CORES --numRuns=$NUM_RUNS --campaignName=$CAMPAIGN_NAME --paramSet=$PARAM_SET
done

declare -a APP_RATES=("50Mbps" "100Mbps" "200Mbps")
for APP_RATE in "${APP_RATES[@]}"; do
  ## Joint run and plot
  srun python3 sem-conference-showcase-fixed-app-rate.py --cores=$CORES --numRuns=$NUM_RUNS --campaignName=$CAMPAIGN_NAME --appRate=$APP_RATE
done
