#!/bin/bash

#SBATCH --job-name parallel_run_11ad_sem_slurm
#SBATCH --output parallel_run_11ad_sem_slurm.o%j
#SBATCH --error parallel_run_11ad_sem_slurm.e%j
#SBATCH --mail-user leccimat@dei.unipd.it
#SBATCH --mail-type ALL
#SBATCH
#SBATCH --time 365-00:00:00
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 24
#SBATCH --partition allgroups
#SBATCH --exclude runner-[04-08,13-15,16-19],gpu1,gpu2
#SBATCH --mem 64G


cd $SLURM_SUBMIT_DIR

# simulation parameters
CORES=24
NUM_RUNS=10
CAMPAIGN_NAME=e35599
# declare -a PARAM_SETS=("basic" "onoff" "onoff_stdev" "spPeriodicity" "onoffPeriodicity" "mcs" "numStas" "smartStart" "accessCbapIfAllocated")
declare -a PARAM_SETS=("mcs")

# activate conda env
source /nfsd/opt/anaconda37/anaconda.sh
source activate /nfsd/signet3/leccimat/private/conda_envs/11ad-env

# compile ns-3
# NOTE: the optimized build is not working properly on the blade
./waf configure --disable-examples --disable-tests --disable-python --enable-modules='applications','core','internet','point-to-point','wifi','flow-monitor','spectrum' --enable-static -d debug --out=build/
./waf build

for PARAM_SET in "${PARAM_SETS[@]}"; do
  # run simulations for param set
  srun python3 sem-conference-showcase-run.py --cores=$CORES --numRuns=$NUM_RUNS --campaignName=$CAMPAIGN_NAME --paramSet=$PARAM_SET
  # sbatch a separate job for plotting
  sbatch plot_11ad_sem_slurm $NUM_RUNS $CAMPAIGN_NAME $PARAM_SET
done
