#!/bin/bash

#SBATCH --job-name plot_11ad_sem
#SBATCH --output plot_11ad_sem.o%j
#SBATCH --error plot_11ad_sem.e%j
#SBATCH --mail-user leccimat@dei.unipd.it
#SBATCH --mail-type ALL
#SBATCH
#SBATCH --time 365-00:00:00
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 1
#SBATCH --partition allgroups
# #SBATCH --exclude runner-[04-08,13-15,16-19],gpu1,gpu2
#SBATCH --mem 32G

cd $SLURM_SUBMIT_DIR

# plot params
NUM_RUNS=$1
CAMPAIGN_NAME=$2
PARAM_SET=$3

# activate conda env
source /nfsd/opt/anaconda37/anaconda.sh
source activate /nfsd/signet3/leccimat/private/conda_envs/11ad-env

# plot
# NOTE: just 1 core needed
echo running: srun python3 sem-conference-showcase-plot.py --numRuns=$NUM_RUNS --campaignName=$CAMPAIGN_NAME --paramSet=$PARAM_SET
srun python3 sem-conference-showcase-plot.py --numRuns=$NUM_RUNS --campaignName=$CAMPAIGN_NAME --paramSet=$PARAM_SET
